name: thesis-exploratory
channels:
 - anaconda
 - conda-forge
 - plotly
dependencies:
 - python=3.8
 - jupyterlab>=3
 - ipywidgets>=7.6
 - plotly=5.3.1
 - jupyter-dash
 - opencv
 - scikit-image
 - scikit-learn
