[settings] 
env="cuda"
path = './gdrive/MyDrive/mt/data/'
output = './gdrive/MyDrive/mt/data/'
experiment_name = 'base_line'

[params]
num_epochs = 1
batch_size = 4
lr = 0.01
shuffle = True
optimizer = 'Adam'
center_crop = 32
normalize_0 = 0.5
normalize_1 = 0.5
normalize_2 = 0.5
normalize_3 = 0.5
normalize_4 = 0.5
normalize_5 = 0.5

[dml_params]
TripletMarginMiner_margin = 0.2
TripletMarginLoss_margin = 0.2
type_of_triplets = "semihard"
ThresholdReducer_low = 0
distance = 'CosineSimilarity'
loss_function = 'TripletMarginLoss'
miner = 'TripletMarginMiner'
reducer = 'ThresholdReducer'
include_accuracies = ('AMI','NMI', 'mean_average_precision', 'mean_average_precision_at_r', 'precision_at_1', 'r_precision', 'precision_at_2')
precision_at_1_k = 1